---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(here)

community_belonging <- read_csv(here("clean_data/community_belonging.csv"))
```
```{r}
community_belonging %>% 
  filter(area == "Scotland", year == 2019, measurement == "Percent",
         walking_distance_to_nearest_greenspace != "All",
         walking_distance_to_nearest_greenspace != "Don't Know") %>% 
  group_by(walking_distance_to_nearest_greenspace) %>% 
  summarise(mean_score = mean(belonging_score)) %>% 
  ggplot(aes(walking_distance_to_nearest_greenspace, mean_score)) +
  geom_col()
```
```{r}
community_belonging %>% 
  filter(area == "Scotland", measurement == "Percent",
         gender != "All") %>% 
  group_by(gender, year) %>% 
  summarise(mean_score = mean(belonging_score)) %>% 
  ggplot(aes(year, mean_score, colour = gender)) +
  geom_line()
```



```{r}
community_belonging %>% 
  filter(area == "Scotland", year == 2019, measurement == "Percent",
         gender != "All") %>% 
  ggplot(aes(community_belonging, value, fill = community_belonging)) +
  geom_col() +
  facet_wrap(~gender)
```

```{r}
neighbourhood_rating <- read_csv(here("clean_data/neighbourhood_rating.csv"))
neighbourhood_rating
```
```{r}
neighbourhood_rating %>% 
  filter(area == "Scotland", measurement == "Percent",
         !walking_distance_to_nearest_greenspace %in% c("All", "Don't Know")) %>% 
  group_by(walking_distance_to_nearest_greenspace, year) %>% 
  summarise(mean_score = mean(neighbourhood_score)) %>% 
  ggplot(aes(year, mean_score, colour = walking_distance_to_nearest_greenspace)) +
  geom_line()
```
```{r}
neighbourhood_rating %>% 
  filter(area == "Scotland", measurement == "Percent",
         !walking_distance_to_nearest_greenspace %in% c("All", "Don't Know"),
         year == 2019) %>% 
  group_by(walking_distance_to_nearest_greenspace) %>% 
  summarise(mean_score = mean(neighbourhood_score)) %>% 
  ggplot(aes(walking_distance_to_nearest_greenspace, mean_score)) +
  geom_col()
```


```{r}
neighbourhood_rating %>% 
  group_by(walking_distance_to_nearest_greenspace) %>% 
  summarise(count = n())
```
```{r}
(102/(3708+915))*100
```
# Join the data?
```{r}
community_belonging
neighbourhood_rating
```
```{r}
neighbourhood_rating_id <- neighbourhood_rating %>% 
  mutate(rating = case_when(
    neighbourhood_rating == "Very good" ~ 5,
    neighbourhood_rating == "Fairly good" ~ 4,
    neighbourhood_rating == "No opinion" ~ 3,
    neighbourhood_rating == "Fairly poor" ~ 2,
    neighbourhood_rating == "Very poor" ~ 1
  ),
  measurement = case_when(
    str_detect(measurement, "Lower") ~ "Lower",
    str_detect(measurement, "Upper") ~ "Upper",
    .default = "Percent"
  )) %>% 
  rowwise() %>% 
  mutate(
    id = str_c(feature_code, year, measurement, gender,
             urban_rural_classification, simd_quintiles, type_of_tenure,
             household_type, ethnicity,
             walking_distance_to_nearest_greenspace, rating)
  ) %>% 
  ungroup() %>% 
  select(-neighbourhood_rating) %>% 
  rename("neighbourhood_value" = value) 

community_belonging_id <- community_belonging %>% 
  mutate(rating = case_when(
    community_belonging == "Not at all strongly" ~ 1,
    community_belonging == "Not very strongly" ~ 2,
    community_belonging == "Don't know" ~ 3,
    community_belonging == "Fairly strongly" ~ 4,
    community_belonging == "Very strongly" ~ 5
  ),
  measurement = case_when(
    str_detect(measurement, "Lower") ~ "Lower",
    str_detect(measurement, "Upper") ~ "Upper",
    .default = "Percent"
  )) %>% 
  rowwise() %>% 
  mutate(
    id = str_c(feature_code, year, measurement, gender,
             urban_rural_classification, simd_quintiles, type_of_tenure,
             household_type, ethnicity,
             walking_distance_to_nearest_greenspace, rating)
  ) %>% 
  ungroup() %>% 
  select(-community_belonging) %>% 
  rename("community_value" = value)
```

```{r}
ratings_joined <- neighbourhood_rating_id %>% 
  select(-c(feature_code, year, measurement, gender,
            urban_rural_classification, simd_quintiles, type_of_tenure,
            household_type, ethnicity, area,
            walking_distance_to_nearest_greenspace, rating)) %>% 
  full_join(community_belonging_id, by = join_by(id)) %>% 
  select(rating, measurement, community_value, belonging_score,
         neighbourhood_value, neighbourhood_score, area, year,
         gender:walking_distance_to_nearest_greenspace)
```

```{r}
neighbourhood_rating %>% 
  distinct()
neighbourhood_rating
```








